# Generated by Django 3.1.1 on 2020-10-16 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('onSaleProduct', '0002_auto_20200929_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsaleproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
    ]
