# Generated by Django 3.1.1 on 2020-10-22 00:47

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('info', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('represent_image', models.ImageField(blank=True, upload_to='product/')),
                ('sub_name', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('w', 'withdrawn')], default='d', max_length=1)),
            ],
        ),
    ]
