# Generated by Django 3.1.1 on 2020-10-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
