# Generated by Django 3.0.8 on 2020-10-18 15:16

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
