# Generated by Django 3.1.1 on 2020-10-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201017_1615'),
        ('product', '0005_auto_20201017_1905'),
    ]

    operations = [
    ]
