# Generated by Django 3.1.1 on 2020-10-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_merge_20201018_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='represent_image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
