# Generated by Django 3.0.8 on 2020-10-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopInfo',
        ),
    ]
