# Generated by Django 3.1.1 on 2020-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPurchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
