# Generated by Django 3.0.6 on 2020-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPurchase', '0002_auto_20200929_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codenumber', models.IntegerField()),
                ('code', models.CharField(default='[1,2,3,4]', max_length=255)),
            ],
        ),
    ]
