# Generated by Django 3.1.1 on 2020-10-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerPurchase', '0003_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
